### ISSUE TITLE
Issues with rapid pushes

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-conex#12]
```
push or pull ${accountid}.dkr.ecr.us-east-1.amazonaws.com/${reponame} is already in progress
```

If this occurs conex will exit, watchbot will retry the job and send an error notification. Desired behavior would be a silent retry (exit code 4)

**Comment by yhahn** [comment]
Scripted some rapid-fire pushes and all of them built successfully. https://github.com/mapbox/ecs-conex/pull/48 switched to tagging images by `repo:gitsha` at build time so we shouldn't see this conflict occur unless we get the same commit notification twice.
