### ISSUE TITLE
ecs-conex Node 4 EoL

### ISSUE THREAD

**Issue by agius** [mapbox/ecs-conex#133]
Hello @taraadiseshan ! I’m a bot from your friendly neighborhood security team! Our systems have detected a lambda function in this repository running Node 4 (or older). Node 4 officially went end-of-life on April 30 of this year, and is no longer supported or receiving security patches from the Node community. As such, we’d like to get this repo updated at your earliest convenience.

Our systems aren’t perfect, so it’s possible this issue was created in error:

- if there is nothing in this repo running outdated Node, please leave a comment to that effect and close the issue
- if this repo is deprecated, no longer in use, or not deployed on our infrastructure, please leave a comment to that effect and close the issue
- if you are not the right person to contact about this codebase, please leave a comment and tag in the most appropriate person or team you know of to handle it

Thank you so much for your help! If you have any questions or concerns, don’t hesitate to reach out!

Best,
~ Versioning Looker-Outer Bot 3001™

![updating-cat-frozen](https://user-images.githubusercontent.com/162151/43170981-c5c35abe-8f5c-11e8-82ba-51ac2672bf52.gif)

**Comment by vsmart** [comment]
Thanks for the heads up @agius! I've grabbed this since the project falls under the scope of @mapbox/assembly-line team. Thanks.
