### ISSUE TITLE
Can webhooks work?

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-conex#3]
API Gateway allows you to create an API key for your endpoint, and then expects that key to be provided as the `x-api-key` header in POST requests to the endpoint.

Github, on the other hand, allows you to specify a secret, and then uses that to provide an HMAC digest of the payload as the `X-Hub-Signature` header in the POST request.

I emailed Github support to try and learn if they have any intention of ever supporting custom headers. An alternative would be to:

- configure api gateway to reject any request lacking the `X-Hub-Signature` header
- setup the lambda function to check the `X-Hub-Signature` header against the expected value for the payload provided, and proceed if acceptable.

cc @zmully

**Comment by zmully** [comment]
I see you stumbled on the same issue with Github as I did. Right now, the chances of the endpoint being found and abused isn't high, but I agree that a bit more input sanitation is a good practice to start with. 

I think we go with option 2 right now, I very much doubt Github is in any rush to provide custom header functionality, being that they still haven't figured out how to provide preview functionality for gists. 

The API key can be passed in by streambot or by API Gateway as a input parameter. I lean towards the simplicity of streambot, but we can't expect all functions to be streambotted right? I really don't want to go down this rabbit hole with API Gateway, but let me know @rclark what your sense of this is.

**Comment by rclark** [comment]
From Github support:

> adding support for custom headers is already on our wishlist for webhooks, but I can't promise when it might happen (probably won't in the near future)

[The lambda code for the webhook](https://github.com/mapbox/ecs-conex/blob/1dc4a1ba866d48dbdb479868472a89e37b5322f2/cloudformation/ecs-conex.template.json#L422-L464) is simple enough that its included in-line, which means no streambot required.

I'll take a stab today at building the HMAC implementation.
