### ISSUE TITLE
--no-cache all the builds

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-conex#30]
We should always build fresh images, without relying on a previous cache. This will make conex builds take longer, but it will insure that conex builds are in sync with builds that may be done locally or on other parts of a CI pipeline (e.g. travis or circle)

- [x] remove the code which attempts to download a `before` image
- [x] add code that refuses a build if the `after` image already exists in ECR
- [x] specify `--no-cache` on all builds
- [ ] (victory lap) this allows us to **always** remove the image we just built after it has been uploaded to ECR (see #29)

cc @emilymdubois @jakepruitt

**Comment by rclark** [comment]
Fixed in #48

**Comment by jakepruitt** [comment]
I really like this!!! This will be so nice in the future
