### ISSUE TITLE
github ci status lied

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/ecs-conex#40]
@rclark said I could open a "ecs-conex lied to me" ticket...

![lies](https://cloud.githubusercontent.com/assets/7933805/17119251/b3e19fee-5292-11e6-8ae4-88a6f0067336.jpg)

Even though my image failed to build.

**Comment by rclark** [comment]
[I believe the problem is here](https://github.com/mapbox/ecs-conex/blob/master/utils.sh#L134-L135), in tandem with #34

To break down the scenario into a simple case, we are basically doing this:

```bash
#!/usr/bin/env bash

set -e

function check_receives() {
    echo "Job received 4 times, aborting build"
    return 3
}

function cleanup() {
    echo $1
    echo "If that was a 0, we sent a complete message to github"
}

trap "cleanup $?" EXIT

check_receives
```

The `cleanup $?` is sending a `0` to the cleanup function, which marks the build job successful.
