### ISSUE TITLE
ecs-conex and tags

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-conex#60]
A moment ago I committed be77d88112aa9c057b4cbe98043352b7c58295d2, tagged it as `v0.2.0` and then `git push && git push --tags`.

These two pushes resulted in two conex jobs, but the ECR repository **did not** end up with an image tagged with the git sha -- only the `v0.2.0` image exists. My hunch is that because the two images are identical, ECR doesn't retain both? This could lead to a botched deploy if the deploy tool assumes that it can use the sha in the stack's `GitSha` parameter.

I'm not sure if there's a way to mitigate this, maybe we just need to document the behavior?

cc @emilymdubois @yhahn @emilymcafee

**Comment by perrygeo** [comment]
I wasn't able to reproduce this. Pushed a commit then a tag and got both images in the registry

![screen shot 2016-11-02 at 3 17 51 pm](https://cloud.githubusercontent.com/assets/1151287/19944081/9491db8c-a110-11e6-9312-e83103668c49.jpg)

**Comment by rclark** [comment]
That's good to hear + more consistent with behavior we've seen. I must've misdiagnosed something originally.

**Comment by perrygeo** [comment]
So I just experienced the opposite problem from what you described in the original post.

I committed, `git push`, waited until I could see the gitsha tag in the registry.

Then ~20 minutes later, I tagged the commit, `git push --tags`. conex built the image but skipped pushing it to registry

```
found existing image for 3bd194aead6eebfe75c18ec5d47c6b7133f08d55 in us-east-1, skipping push
```

The code is https://github.com/mapbox/ecs-conex/blob/master/utils.sh#L123-L137

Quick solution might be to run `exact_match` before testing `image_exists`?

**Comment by rclark** [comment]
I think that there are two important things here:

1. An existing SHA image should not block the `exact_match` code from being executed. This solves the problem that you encountered @perrygeo.
2. The `exact_match` code should be unable to overwrite an existing tagged image. We never want images to be overwritten.
