### ISSUE TITLE
log-in to private ECR before building image

### ISSUE THREAD

**Issue by isiyu** [mapbox/ecs-conex#61]
Sometimes the base images used by Dockerfiles are located in private ECR repos. `ecs-conex` needs an option to log into private repos as needed to grab base images before building the docker file.

**Comment by rclark** [comment]
We currently [log in to each ECR region as we push images to them](https://github.com/mapbox/ecs-conex/blob/master/utils.sh#L119). Instead, we should log into all 3 regions [immediately prior to running `docker build`](https://github.com/mapbox/ecs-conex/blob/master/ecs-conex.sh#L45). This will enable to builds to fetch images from any region specified by the `FROM` action in a Dockerfile.

**Comment by isiyu** [comment]
thanks @rclark
