### ISSUE TITLE
Install aws-cli w/o pip

### ISSUE THREAD

**Issue by miccolis** [mapbox/ecs-conex#70]
I've seen pip have really old version of the aws cli and I've starting only installing it directly from AWS. Directions are at http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-bundle-other-os 

tl;dr; 

```
$ curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
$ unzip awscli-bundle.zip
$ sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
```

/cc @rclark

**Comment by rclark** [comment]
I've not been bitten by this -- did it cause problems for you?

**Comment by miccolis** [comment]
Naw, no problems - I just saw the code in here and wanted to flag it.

**Comment by miccolis** [comment]
Ok, I double checked the versions and pip is up to date. I'm fine to chalk this up to pip related PTSD from the one time, like 5 years ago, when pip repos were down...

Only good argument to make here is that avoiding a python-pip package install could reduce image size. Totally not critical.
