### ISSUE TITLE
Provide GitHub token as build-arg

### ISSUE THREAD

**Issue by dnomadb** [mapbox/ecs-conex#76]
ecs-conex already has a GitHub token for cloning the repo that it is building. However, we'd need to pass in the token to the dockerfile itself if _another_ private repo (for instance, a python module in development).

Another block like so https://github.com/mapbox/ecs-conex/blob/master/utils.sh#L79-L82 should work.

cc @jacquestardie @rclark

**Comment by perrygeo** [comment]
closed via #77
