### ISSUE TITLE
Provide Better Error Message for Timeout

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/ecs-conex#93]
It seems like there is a default limit of 20 minutes for building Docker images set [here](https://github.com/mapbox/ecs-conex/blob/ee0891bb9baf747aaa9cd85939e26c32936e0653/cloudformation/ecs-conex.template.js#L26).

For more involved Docker images this is often not enough. I didn't get any error message for hitting the timeout, all I saw was Docker build getting randomly killed during building the image.

Is it possible to issue a timeout-reached error message?

**Comment by rclark** [comment]
Actually that timeout != an enforced limit on build time, but still may need to be increased.

That timeout value corresponds to handling of SQS messages. Conex gets a message, which starts a clock ticking. If your build exits successfully, conex removes the SQS message from the queue. If your build fails, it returns the message. That timeout actually means that if your build does not exit in 20 min, the SQS message will be automatically dropped back to the queue. It **will not** cancel your running build, but your build will probably get attempted again.

If you're seeing your builds are actually failing, there may be another issue. Feel free to ping me in chat.

**Comment by daniel-j-h** [comment]
Thanks for the explanation. Let's close this issue then and find the root cause for workers getting killed.
